docker network create cassandra-net

docker run --name my-cassandra \
--network cassandra-net \
-p 9042:9042
-d cassandra:latest	

 docker run -it --network some-network --rm cassandra cqlsh some-cassandra
 
 docker run -p27017:27017 -d mongo:latest